
Showing logs for build [32mmarthydavid-python-own-demo-mas-phd2n-6[0m stage [32mfrom-build-pack[0m and container [32mstep-credential-initializer-cszfn[0m
{"level":"warn","ts":1572693026.591717,"logger":"fallback-logger","caller":"logging/config.go:69","msg":"Fetch GitHub commit ID from kodata failed: \"ref: refs/heads/master\" is not a valid GitHub commit ID"}
{"level":"info","ts":1572693026.593242,"logger":"fallback-logger","caller":"creds-init/main.go:40","msg":"Credentials initialized."}

Showing logs for build [32mmarthydavid-python-own-demo-mas-phd2n-6[0m stage [32mfrom-build-pack[0m and container [32mstep-working-dir-initializer-p58cr[0m
{"level":"warn","ts":1572693027.273165,"logger":"fallback-logger","caller":"logging/config.go:69","msg":"Fetch GitHub commit ID from kodata failed: open /var/run/ko/HEAD: no such file or directory"}
{"level":"info","ts":1572693027.2834473,"logger":"fallback-logger","caller":"bash/main.go:65","msg":"Successfully executed command \"mkdir -p /workspace/source\""}

Showing logs for build [32mmarthydavid-python-own-demo-mas-phd2n-6[0m stage [32mfrom-build-pack[0m and container [32mstep-place-tools[0m

Showing logs for build [32mmarthydavid-python-own-demo-mas-phd2n-6[0m stage [32mfrom-build-pack[0m and container [32mstep-git-source-marthydavid-python-own-demo-mas-gs46x[0m
{"level":"warn","ts":1572693033.33859,"logger":"fallback-logger","caller":"logging/config.go:69","msg":"Fetch GitHub commit ID from kodata failed: \"ref: refs/heads/master\" is not a valid GitHub commit ID"}
{"level":"info","ts":1572693034.6773424,"logger":"fallback-logger","caller":"git/git.go:102","msg":"Successfully cloned https://github.com/***********/python-own-demo.git @ v0.0.6 in path /workspace/source"}

Showing logs for build [32mmarthydavid-python-own-demo-mas-phd2n-6[0m stage [32mfrom-build-pack[0m and container [32mstep-git-merge[0m
Using SHAs from PULL_REFS=master:053917ecebb610d1d89386540a3f86645709b905
WARNING: no SHAs to merge, falling back to initial cloned commit

Showing logs for build [32mmarthydavid-python-own-demo-mas-phd2n-6[0m stage [32mfrom-build-pack[0m and container [32mstep-setup-jx-git-credentials[0m
Generated Git credentials file /workspace/xdg_config/git/credentials

Showing logs for build [32mmarthydavid-python-own-demo-mas-phd2n-6[0m stage [32mfrom-build-pack[0m and container [32mstep-build-python-unittest[0m

----------------------------------------------------------------------
Ran 0 tests in 0.000s

OK

Showing logs for build [32mmarthydavid-python-own-demo-mas-phd2n-6[0m stage [32mfrom-build-pack[0m and container [32mstep-build-container-build[0m
[36mINFO[0m[0000] Downloading base image python:onbuild        
2019/11/02 11:10:36 No matching credentials were found, falling back on anonymous
[36mINFO[0m[0001] Error while retrieving image from cache: getting file info: stat /workspace/sha256:43780a8431c53f4afd734ad795e03127c0c607337a60639c5903a51a03535c22: no such file or directory 
[36mINFO[0m[0001] Downloading base image python:onbuild        
2019/11/02 11:10:37 No matching credentials were found, falling back on anonymous
[36mINFO[0m[0002] Executing 3 build triggers                   
[36mINFO[0m[0002] Using files from context: [/workspace/source/requirements.txt] 
[36mINFO[0m[0002] Checking for cached layer docker-registry.**.k8s2.marthy.xyz/todo/cache:f96ea06eb1dc1e896fb6ba60e374488f43e9918d4fe1cb30c5f26c8dea340a73... 
2019/11/02 11:10:39 No matching credentials were found, falling back on anonymous
[36mINFO[0m[0003] Using caching version of cmd: RUN pip install --no-cache-dir -r requirements.txt 
[36mINFO[0m[0003] Using files from context: [/workspace/source] 
[36mINFO[0m[0003] Using files from context: [/workspace/source/requirements.txt] 
[36mINFO[0m[0003] cmd: EXPOSE                                  
[36mINFO[0m[0003] Adding exposed port: 8080/tcp                
[36mINFO[0m[0003] Skipping unpacking as no commands require it. 
[36mINFO[0m[0003] Taking snapshot of full filesystem...        
[36mINFO[0m[0003] Using files from context: [/workspace/source/requirements.txt] 
[36mINFO[0m[0003] COPY requirements.txt /usr/src/app/          
[36mINFO[0m[0003] Taking snapshot of files...                  
[36mINFO[0m[0003] RUN pip install --no-cache-dir -r requirements.txt 
[36mINFO[0m[0003] Found cached layer, extracting to filesystem 
[36mINFO[0m[0003] Taking snapshot of files...                  
[36mINFO[0m[0003] Using files from context: [/workspace/source] 
[36mINFO[0m[0003] COPY . /usr/src/app                          
[36mINFO[0m[0003] Taking snapshot of files...                  
[36mINFO[0m[0003] Using files from context: [/workspace/source/requirements.txt] 
[36mINFO[0m[0003] COPY requirements.txt .                      
[36mINFO[0m[0003] Taking snapshot of files...                  
[36mINFO[0m[0003] ENV PORT 8080                                
[36mINFO[0m[0003] No files changed in this command, skipping snapshotting. 
[36mINFO[0m[0003] EXPOSE 8080                                  
[36mINFO[0m[0003] cmd: EXPOSE                                  
[36mINFO[0m[0003] Adding exposed port: 8080/tcp                
[36mINFO[0m[0003] No files changed in this command, skipping snapshotting. 
[36mINFO[0m[0003] ENTRYPOINT ["python"]                        
[36mINFO[0m[0003] No files changed in this command, skipping snapshotting. 
[36mINFO[0m[0003] CMD ["app.py"]                               
[36mINFO[0m[0003] No files changed in this command, skipping snapshotting. 
2019/11/02 11:10:39 existing blob: sha256:1c7fe136a31e13a1c879245672184ced3b9fc590989ba42a522a57b071a9c1aa
2019/11/02 11:10:39 existing blob: sha256:e2c0fb34dff3a1d32346b92e53fb88a14d1987b402a2348cb379c039687fabe2
2019/11/02 11:10:39 existing blob: sha256:f0db43b9b8da254cebc77bf871006df01219e195b9853616b9f708f124a00f3a
2019/11/02 11:10:39 existing blob: sha256:06854774e2f35e4763103a446112c67322913a6177bea69eb49663e0166e6d6d
2019/11/02 11:10:39 existing blob: sha256:e10b68fb77e6e91453cd4c1b02e2d77aa23a857cd8eb250617129d074478e1a5
2019/11/02 11:10:39 existing blob: sha256:e96bc319bce0351d1157092352bc5f85f8800c745388e60e86d06dec99285b45
2019/11/02 11:10:39 existing blob: sha256:490280dbcfb772eb5731f059e38fcfacaeb75b4d005af7c249fd51926db2bd62
2019/11/02 11:10:39 existing blob: sha256:2d21c767035c4593de8bf7ad9781aa83ba110871d1a50871192f4e3480e6f11d
2019/11/02 11:10:39 existing blob: sha256:ece825d3308bbf98f708d95475ccd880497a1e2979ff4ef2534d49049a18488f
2019/11/02 11:10:40 pushed blob: sha256:943940d46e733b6d45b186dfd62c18f7f02a94fbe65dfb7a75a06b28521acbf2
2019/11/02 11:10:40 pushed blob: sha256:0dfe77e7af4141bd982280de0bd74f79590a41670cf741df65c940fb591e9ecf
2019/11/02 11:10:40 pushed blob: sha256:0319e0b61ae2a946327927f58887fca74289434e74d514e548c5b82aaf145eb3
2019/11/02 11:10:40 pushed blob: sha256:499a7dd431ebcbb85a8559d3d7a8ac3cc6169daf936843fefb112634e9d1e326
2019/11/02 11:10:40 pushed blob: sha256:c9a499b6b809f2a81b15be7de6b0b0890696b59bd4be04a5f1685034b5f9fba6
2019/11/02 11:10:40 docker-registry.**.k8s2.marthy.xyz/***********/python-own-demo:0.0.6: digest: sha256:7b0170e2e87fa24d79f8d374ed86c389758e3bfb470ea90bd423cbcf61debb3c size: 2384

Showing logs for build [32mmarthydavid-python-own-demo-mas-phd2n-6[0m stage [32mfrom-build-pack[0m and container [32mstep-build-post-build[0m
no CVE provider running in the current ** namespace so skip adding image to be analysed

Showing logs for build [32mmarthydavid-python-own-demo-mas-phd2n-6[0m stage [32mfrom-build-pack[0m and container [32mstep-promote-changelog[0m
Converted /workspace/source/charts/python-own-demo to an unshallow repository
Generating change log from git ref e052bf21d342c2d4b13017237ad96a5ab4775852 => 07f17f73b9d7b69fecf583f54e750d07ba61f265
Associating user *********** in users.jenkins.io with email marthy.david@gmail.com to git GitProvider user with login -0 as emails match
Adding label jenkins.io/git-github-userid=-0 to user *********** in users.jenkins.io
WARNING: Failed to enrich commit 96598ded9f68fec5eaa1dd1325516fa20846facc with issues: User.jenkins.io "***********" is invalid: metadata.labels: Invalid value: "-0": a valid label must be an empty string or consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyValue',  or 'my_value',  or '12345', regex used for validation is '(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?')
Associating user *********** in users.jenkins.io with email marthy.david@gmail.com to git GitProvider user with login -0 as emails match
Adding label jenkins.io/git-github-userid=-0 to user *********** in users.jenkins.io
WARNING: Failed to enrich commit 96598ded9f68fec5eaa1dd1325516fa20846facc with issues: User.jenkins.io "***********" is invalid: metadata.labels: Invalid value: "-0": a valid label must be an empty string or consist of alphanumeric characters, '-', '_' or '.', and must start and end with an alphanumeric character (e.g. 'MyValue',  or 'my_value',  or '12345', regex used for validation is '(([A-Za-z0-9][-A-Za-z0-9_.]*)?[A-Za-z0-9])?')
Finding issues in commit messages using git format
WARNING: No release found for ***********/python-own-demo and tag v0.0.6 so creating a new release
Updated the release information at https://github.com/***********/python-own-demo/releases/tag/v0.0.6
generated: /workspace/source/charts/python-own-demo/templates/release.yaml
Created Release python-own-demo-0-0-6 resource in namespace **
Updating PipelineActivity ***********-python-own-demo-master-6 with version 0.0.6
Updated PipelineActivities ***********-python-own-demo-master-6 with release notes URL: https://github.com/***********/python-own-demo/releases/tag/v0.0.6

Showing logs for build [32mmarthydavid-python-own-demo-mas-phd2n-6[0m stage [32mfrom-build-pack[0m and container [32mstep-promote-helm-release[0m
WARNING: No $CHART_REPOSITORY defined so using the default value of: http://jenkins-x-chartmuseum:8080
Adding missing Helm repo: storage.googleapis.com https://storage.googleapis.com/chartmuseum.jenkins-x.io
Successfully added Helm repository storage.googleapis.com.
Adding missing Helm repo: jenkins-x-chartmuseum http://jenkins-x-chartmuseum:8080
Successfully added Helm repository jenkins-x-chartmuseum.
WARNING: No $CHART_REPOSITORY defined so using the default value of: http://jenkins-x-chartmuseum:8080
Uploading chart file python-own-demo-0.0.6.tgz to http://jenkins-x-chartmuseum:8080/api/charts
Received 201 response: {"saved":true}

Showing logs for build [32mmarthydavid-python-own-demo-mas-phd2n-6[0m stage [32mfrom-build-pack[0m and container [32mstep-promote-jx-promote[0m
WARNING: prow based install so skip waiting for the merge of Pull Requests to go green as currently there is an issue with gettingstatuses from the PR, see https://github.com/jenkins-x/**/issues/2410
Promoting app python-own-demo version 0.0.6 to namespace **-staging
Created Pull Request: https://github.com/***********/environment-kittenshadow-staging/pull/4
Added label updatebot to Pull Request https://github.com/***********/environment-kittenshadow-staging/pull/4
got git provider status pending from PR https://github.com/***********/environment-kittenshadow-staging/pull/4
got git provider status pending from PR https://github.com/***********/environment-kittenshadow-staging/pull/4
got git provider status pending from PR https://github.com/***********/environment-kittenshadow-staging/pull/4
Pull Request https://github.com/***********/environment-kittenshadow-staging/pull/4 is merged at sha 5d29ecfc76f495a9e4644799947482144417b03f
Pull Request merged but we are not waiting for the update pipeline to complete!
