
Showing logs for build [32mmarthydavid-python-own-demo-pr-z585w-1[0m stage [32mfrom-build-pack[0m and container [32mstep-credential-initializer-rc6sg[0m
{"level":"warn","ts":1572692775.946932,"logger":"fallback-logger","caller":"logging/config.go:69","msg":"Fetch GitHub commit ID from kodata failed: \"ref: refs/heads/master\" is not a valid GitHub commit ID"}
{"level":"info","ts":1572692775.948059,"logger":"fallback-logger","caller":"creds-init/main.go:40","msg":"Credentials initialized."}

Showing logs for build [32mmarthydavid-python-own-demo-pr-z585w-1[0m stage [32mfrom-build-pack[0m and container [32mstep-working-dir-initializer-2qm9w[0m
{"level":"warn","ts":1572692776.6129882,"logger":"fallback-logger","caller":"logging/config.go:69","msg":"Fetch GitHub commit ID from kodata failed: open /var/run/ko/HEAD: no such file or directory"}
{"level":"info","ts":1572692776.615742,"logger":"fallback-logger","caller":"bash/main.go:65","msg":"Successfully executed command \"mkdir -p /workspace/source\""}

Showing logs for build [32mmarthydavid-python-own-demo-pr-z585w-1[0m stage [32mfrom-build-pack[0m and container [32mstep-place-tools[0m

Showing logs for build [32mmarthydavid-python-own-demo-pr-z585w-1[0m stage [32mfrom-build-pack[0m and container [32mstep-git-source-marthydavid-python-own-demo-pr-t56jc[0m
{"level":"warn","ts":1572692782.702708,"logger":"fallback-logger","caller":"logging/config.go:69","msg":"Fetch GitHub commit ID from kodata failed: \"ref: refs/heads/master\" is not a valid GitHub commit ID"}
{"level":"info","ts":1572692784.2066011,"logger":"fallback-logger","caller":"git/git.go:102","msg":"Successfully cloned https://github.com/***********/python-own-demo.git @ master in path /workspace/source"}

Showing logs for build [32mmarthydavid-python-own-demo-pr-z585w-1[0m stage [32mfrom-build-pack[0m and container [32mstep-git-merge[0m
Using SHAs from PULL_REFS=master:b0169e3245310e0e0381458c52115c8fb0af4c1d,2:96598ded9f68fec5eaa1dd1325516fa20846facc
DEBUG: ran git fetch --unshallow origin 96598ded9f68fec5eaa1dd1325516fa20846facc: b0169e3245310e0e0381458c52115c8fb0af4c1d: in 
DEBUG: ran git checkout master in 
DEBUG: ran git reset --hard b0169e3245310e0e0381458c52115c8fb0af4c1d in 
DEBUG: ran clean --force -d . in 
DEBUG: ran git merge 96598ded9f68fec5eaa1dd1325516fa20846facc in 
Merged SHA 96598ded9f68fec5eaa1dd1325516fa20846facc with commit message 'Switch logo' into base branch master

Showing logs for build [32mmarthydavid-python-own-demo-pr-z585w-1[0m stage [32mfrom-build-pack[0m and container [32mstep-build-python-unittest[0m

----------------------------------------------------------------------
Ran 0 tests in 0.000s

OK

Showing logs for build [32mmarthydavid-python-own-demo-pr-z585w-1[0m stage [32mfrom-build-pack[0m and container [32mstep-build-container-build[0m
[36mINFO[0m[0000] Downloading base image python:onbuild        
2019/11/02 11:06:27 No matching credentials were found, falling back on anonymous
[36mINFO[0m[0001] Error while retrieving image from cache: getting file info: stat /workspace/sha256:43780a8431c53f4afd734ad795e03127c0c607337a60639c5903a51a03535c22: no such file or directory 
[36mINFO[0m[0001] Downloading base image python:onbuild        
2019/11/02 11:06:29 No matching credentials were found, falling back on anonymous
[36mINFO[0m[0003] Executing 3 build triggers                   
[36mINFO[0m[0003] Using files from context: [/workspace/source/requirements.txt] 
[36mINFO[0m[0003] Checking for cached layer docker-registry.**.k8s2.marthy.xyz/todo/cache:f96ea06eb1dc1e896fb6ba60e374488f43e9918d4fe1cb30c5f26c8dea340a73... 
2019/11/02 11:06:30 No matching credentials were found, falling back on anonymous
[36mINFO[0m[0003] Using caching version of cmd: RUN pip install --no-cache-dir -r requirements.txt 
[36mINFO[0m[0003] Using files from context: [/workspace/source] 
[36mINFO[0m[0003] Using files from context: [/workspace/source/requirements.txt] 
[36mINFO[0m[0003] cmd: EXPOSE                                  
[36mINFO[0m[0003] Adding exposed port: 8080/tcp                
[36mINFO[0m[0003] Skipping unpacking as no commands require it. 
[36mINFO[0m[0003] Taking snapshot of full filesystem...        
[36mINFO[0m[0003] Using files from context: [/workspace/source/requirements.txt] 
[36mINFO[0m[0003] COPY requirements.txt /usr/src/app/          
[36mINFO[0m[0003] Taking snapshot of files...                  
[36mINFO[0m[0003] RUN pip install --no-cache-dir -r requirements.txt 
[36mINFO[0m[0003] Found cached layer, extracting to filesystem 
[36mINFO[0m[0003] Taking snapshot of files...                  
[36mINFO[0m[0003] Using files from context: [/workspace/source] 
[36mINFO[0m[0003] COPY . /usr/src/app                          
[36mINFO[0m[0003] Taking snapshot of files...                  
[36mINFO[0m[0003] Using files from context: [/workspace/source/requirements.txt] 
[36mINFO[0m[0003] COPY requirements.txt .                      
[36mINFO[0m[0003] Taking snapshot of files...                  
[36mINFO[0m[0003] ENV PORT 8080                                
[36mINFO[0m[0003] No files changed in this command, skipping snapshotting. 
[36mINFO[0m[0003] EXPOSE 8080                                  
[36mINFO[0m[0003] cmd: EXPOSE                                  
[36mINFO[0m[0003] Adding exposed port: 8080/tcp                
[36mINFO[0m[0003] No files changed in this command, skipping snapshotting. 
[36mINFO[0m[0003] ENTRYPOINT ["python"]                        
[36mINFO[0m[0003] No files changed in this command, skipping snapshotting. 
[36mINFO[0m[0003] CMD ["app.py"]                               
[36mINFO[0m[0003] No files changed in this command, skipping snapshotting. 
2019/11/02 11:06:30 existing blob: sha256:f0db43b9b8da254cebc77bf871006df01219e195b9853616b9f708f124a00f3a
2019/11/02 11:06:30 existing blob: sha256:2d21c767035c4593de8bf7ad9781aa83ba110871d1a50871192f4e3480e6f11d
2019/11/02 11:06:30 existing blob: sha256:490280dbcfb772eb5731f059e38fcfacaeb75b4d005af7c249fd51926db2bd62
2019/11/02 11:06:30 existing blob: sha256:06854774e2f35e4763103a446112c67322913a6177bea69eb49663e0166e6d6d
2019/11/02 11:06:30 existing blob: sha256:e96bc319bce0351d1157092352bc5f85f8800c745388e60e86d06dec99285b45
2019/11/02 11:06:30 existing blob: sha256:ece825d3308bbf98f708d95475ccd880497a1e2979ff4ef2534d49049a18488f
2019/11/02 11:06:30 existing blob: sha256:1c7fe136a31e13a1c879245672184ced3b9fc590989ba42a522a57b071a9c1aa
2019/11/02 11:06:30 existing blob: sha256:e2c0fb34dff3a1d32346b92e53fb88a14d1987b402a2348cb379c039687fabe2
2019/11/02 11:06:30 existing blob: sha256:e10b68fb77e6e91453cd4c1b02e2d77aa23a857cd8eb250617129d074478e1a5
2019/11/02 11:06:31 pushed blob: sha256:d4a79975c948e6fe77212a49f344da821825c8764049099e103999b6e0cbedac
2019/11/02 11:06:31 pushed blob: sha256:5aaf8024cc5aed7c6a790eee86997997a3b27329809e86561a876a2270b8077c
2019/11/02 11:06:31 pushed blob: sha256:a060a6ea287b5724cf5cdb26a5d072f3045dd62f0c5efac2c55077ac61dc7019
2019/11/02 11:06:31 pushed blob: sha256:fddb4a91b25482c986febf2f8cbddcc139a343b456967269f6e24bee42e71947
2019/11/02 11:06:31 pushed blob: sha256:7b83a2a27ed476edfd140d3b1e5713975e21f93fe57b6d9fe1cc99e4a378b78e
2019/11/02 11:06:31 docker-registry.**.k8s2.marthy.xyz/***********/python-own-demo:0.0.0-SNAPSHOT-PR-2-1: digest: sha256:eed1e7958c62b08b301c6e880d76ae8288656bc4b7d904c97cebcf1dba2f2025 size: 2385

Showing logs for build [32mmarthydavid-python-own-demo-pr-z585w-1[0m stage [32mfrom-build-pack[0m and container [32mstep-postbuild-post-build[0m
no CVE provider running in the current ** namespace so skip adding image to be analysed

Showing logs for build [32mmarthydavid-python-own-demo-pr-z585w-1[0m stage [32mfrom-build-pack[0m and container [32mstep-promote-make-preview[0m
sed -i -e "s/version:.*/version: 0.0.0-SNAPSHOT-PR-2-1/" Chart.yaml
sed -i -e "s/version:.*/version: 0.0.0-SNAPSHOT-PR-2-1/" ../*/Chart.yaml
sed -i -e "s|repository:.*|repository: docker-registry.**.k8s2.marthy.xyz\/***********\/python-own-demo|" values.yaml
sed -i -e "s/tag:.*/tag: 0.0.0-SNAPSHOT-PR-2-1/" values.yaml
echo "  version: 0.0.0-SNAPSHOT-PR-2-1" >> requirements.yaml
** step helm build
WARNING: No $CHART_REPOSITORY defined so using the default value of: http://jenkins-x-chartmuseum:8080
Adding missing Helm repo: storage.googleapis.com https://storage.googleapis.com/chartmuseum.jenkins-x.io
Successfully added Helm repository storage.googleapis.com.
Adding missing Helm repo: jenkins-x-chartmuseum http://jenkins-x-chartmuseum:8080
Successfully added Helm repository jenkins-x-chartmuseum.
WARNING: No $CHART_REPOSITORY defined so using the default value of: http://jenkins-x-chartmuseum:8080
Adding missing Helm repo: chartmuseum.jenkins-x.io http://chartmuseum.jenkins-x.io
Successfully added Helm repository chartmuseum.jenkins-x.io.

Showing logs for build [32mmarthydavid-python-own-demo-pr-z585w-1[0m stage [32mfrom-build-pack[0m and container [32mstep-promote-jx-preview[0m
Creating a preview
Commit author email is empty for: 96598ded9f68fec5eaa1dd1325516fa20846facc
Looking for commits in: /workspace/source/
Found commit author match for: *********** with email address: marthy.david@gmail.com
Created environment ***********-python-own-demo-pr-2
Namespace **-***********-python-own-demo-pr-2 created 
expose:
  Annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-delete-policy: hook-succeeded
  config:
    domain: k8s2.marthy.xyz
    exposer: Ingress
    http: "true"
preview:
  image:
    repository: docker-registry.**.k8s2.marthy.xyz/***********/python-own-demo
    tag: 0.0.0-SNAPSHOT-PR-2-1
Cloning the Jenkins X versions repo https://github.com/jenkins-x/jenkins-x-versions.git with ref refs/heads/master to /builder/home/.**/jenkins-x-versions


Updating PipelineActivities ***********-python-own-demo-pr-2-1 which has status Running
WARNING: preview application http://python-own-demo.**-***********-python-own-demo-pr-2.k8s2.marthy.xyz not available, error was 503 503 Service Temporarily Unavailable, delaying for: 793.114244ms
WARNING: preview application http://python-own-demo.**-***********-python-own-demo-pr-2.k8s2.marthy.xyz not available, error was 503 503 Service Temporarily Unavailable, delaying for: 1.660880159s
WARNING: preview application http://python-own-demo.**-***********-python-own-demo-pr-2.k8s2.marthy.xyz not available, error was 503 503 Service Temporarily Unavailable, delaying for: 2.349350039s
WARNING: preview application http://python-own-demo.**-***********-python-own-demo-pr-2.k8s2.marthy.xyz not available, error was 503 503 Service Temporarily Unavailable, delaying for: 2.690253879s
WARNING: preview application http://python-own-demo.**-***********-python-own-demo-pr-2.k8s2.marthy.xyz not available, error was 503 503 Service Temporarily Unavailable, delaying for: 7.253785045s
WARNING: preview application http://python-own-demo.**-***********-python-own-demo-pr-2.k8s2.marthy.xyz not available, error was 503 503 Service Temporarily Unavailable, delaying for: 10.799924342s
WARNING: preview application http://python-own-demo.**-***********-python-own-demo-pr-2.k8s2.marthy.xyz not available, error was 503 503 Service Temporarily Unavailable, delaying for: 13.093403387s
Preview application is now available at: http://python-own-demo.**-***********-python-own-demo-pr-2.k8s2.marthy.xyz
